---
  - hosts: switches
    vars: 
      - license_server_url: 'http://192.168.0.1'
    roles:
      - common

  - hosts: switches
    roles:
      - interfaces

  - hosts: server
    roles:
       - { role: serverbond, tags: 'server' }
