- name: clean out /etc/network/interfaces
  template: src=interfaces.j2 dest=/etc/network/interfaces

- name: interface policy
  cl_interface_policy: 
     allowed: "{{ allowed_list }}"
  tags: allowed

- name: configure loopback
  cl_interface: name=lo addr_method=loopback
  notify: reload networking

- name: configure mgmt
  cl_interface: name=eth0 addr_method=dhcp
  notify: reload networking

- name: configure bridges
  cl_bridge:                                                                                 
      name: "{{ item.key }}"                                                                   
      ports: "{{ item.value.ports }}"                                                            
      vlan_aware: "{{ item.value.vlan_aware|default() }}"                                  
      ipv4:  "{{ item.value.ipv4|default() }}"                                             
      ipv6: "{{ item.value.ipv6|default() }}"                                              
      alias_name: "{{ item.value.alias_name|default() }}"                                  
      addr_method: "{{ item.value.addr_method|default() }}"                                
      mtu: 9000
      vids: "{{ item.value.vids|default() }}"                                              
      virtual_ip: "{{ item.value.virtual_ip|default() }}"                                  
      virtual_mac: "{{ item.value.virtual_mac|default() }}"                                
      mstpctl_treeprio: "{{ item.value.mstpctl_treeprio|default() }}"                      
  with_dict: cl_bridges                                                                       
  notify: reload networking                                                                  
  tags: bridging
                         
- name: configure bonds
  cl_bond:                                                                                   
      name: "{{ item.key }}"                                                                   
      slaves: "{{ item.value.slaves }}"                                                          
      clag_id: "{{ item.value.clag_id|default()}}"                                          
      addr_method: "{{item.value.addr_method|default()}}"
      mtu: 9000
      ipv4: "{{item.value.ipv4|default()}}"
      ipv6: "{{item.value.ipv6|default()}}"                                                
      vids: "{{ item.value.vids|default() }}"                                              
      virtual_ip: "{{ item.value.virtual_ip|default() }}"                                  
      virtual_mac: "{{ item.value.virtual_mac|default() }}"                                
      mstpctl_portnetwork: "{{ item.value.mstpctl_portnetwork|default(0) }}"                
      mstpctl_bpduguard: "{{ item.value.mstpctl_bpduguard|default(0) }}"                    
  with_dict: cl_bonds
  notify: reload networking               
  tags: bonding

- name: configure interfaces
  cl_interface:
      name: "{{ item.key }}"
      ipv4:  "{{ item.value.ipv4|default([]) }}"
      ipv6: "{{ item.value.ipv6|default([]) }}"
      alias_name: "{{ item.value.alias_name|default() }}"
      addr_method: "{{ item.value.addr_method|default() }}"
      speed: "{{ item.value.link_speed|default() }}"
      mtu: 9000
      clagd_enable: "{{ item.value.clagd_enable|default() }}"
      clagd_peer_ip: "{{ item.value.clagd_peer_ip|default() }}"
      clagd_sys_mac: "{{ item.value.clagd_sys_mac|default() }}"
      clagd_priority: "{{ item.value.clagd_priority|default() }}"
      vids: "{{ item.value.vids|default() }}"
      virtual_ip: "{{ item.value.virtual_ip|default() }}"
      virtual_mac: "{{ item.value.virtual_mac|default() }}"
      mstpctl_portnetwork: "{{ item.value.mstpctl_portnetwork|default(0) }}"
      mstpctl_bpduguard: "{{ item.value.mstpctl_bpduguard|default(0) }}"
  with_dict: cl_interfaces
  notify: reload networking
  tags: interfaces
